export const categroy = {
    "Guitars 1" : [
        {name:"Fender", created:true},
        {name:"Gibson", created:false},
        {name:"PRS", created:false},
        {name:"Suhr", created:false},
        {name:"James Tyler", created:false},
    ],
    "Guitars 2" : [
        {name:"Bacchus", created:false},
        {name:"Ibanez", created:false},
        {name:"Momose(Japan)", created:false},
        {name:"Seventy Seven(Hollowbody)", created:false},
        {name:"Musicman", created:false},
    ],
    "Bass 1" : [
        {name:"Fodera", created:false},
        {name:"Alieva Coppolo", created:false},
        {name:"Fender", created:false},
        {name:"Lakland", created:false},
        {name:"MTD", created:false},
        {name:"F-BASS", created:false},
        {name:"PRS", created:false},
    ],
    "Bass 2" : [
        {name:"Ibanez", created:false},
        {name:"Dingwall", created:false},
        {name:"Spector", created:false},
        {name:"Epiphone", created:false},
        {name:"Sandberg", created:false},
    ],
    "Acoustic 1" : [
        {name:"Martin", created:false},
        {name:"Taylor", created:false},
        {name:"Gibson", created:false},
        {name:"PRS", created:false},
        {name:"Furch", created:false},
        {name:"Lakewood", created:false},
    ],
    "Acoustic 2" : [
        {name:"Sigma", created:false},
        {name:"Epiphone", created:false},
        {name:"Cort", created:false},
        {name:"Cordoba", created:false},
        {name:"Godin", created:false},
    ],
    "Recording" : [
        {name:"Audio Interface", created:false},
        {name:"Load Box & IR", created:false},
        {name:"MIC", created:false},
        {name:"Monitor Speaker", created:false},
        {name:"D.I", created:false},
    ],
    "Amp" : [
        {name:"Suhr", created:false},
        {name:"PRS", created:false},
        {name:"Bogner", created:false},
        {name:"Hughes and Kettner", created:false},
        {name:"Revv", created:false},
        {name:"Fender", created:false},
        {name:"Marshall", created:false},
    ],
    "Pedals" : [ // 너무 많아서 인지도 있는 페달만 우선 기입
        {name:"Bogner", created:false},
        {name:"Suhr", created:false},
        {name:"Friedman", created:false},
        {name:"Vertex ", created:false},
        {name:"Revv Amplication", created:false},
        {name:"Mad Professor", created:false},
        {name:"Vemuram", created:false},
    ],
    "Acc/Parts ": [
        {name:"Gotoh Parts", created:false},
        {name:"Gibson Parts", created:false},
        {name:"PRS Parts & ACC", created:false},
        {name:"Gruvgear ", created:false},
        {name:"Gator", created:false},
        {name:"픽업", created:false},
        {name:"스트랩", created:false},
        {name:"관리용품", created:false},
    ],
    "New Arrival":[],
    "Sale":[],
    "Used/Outlet" : [ // 너무 많아서 인지도 있는 페달만 우선 기입
        {name:"Used(중고제품)", created:false},
        {name:"Outlet(아웃렛)", created:false},
    ],
}
export const headlineMiddleInfo=[
    "로그인", "회원가입", "장바구니", "주문조회", 
]

