export const categroy = {
    "Guitars 1" : [
        {name:"Fender", cate:1345, created:true},
        {name:"Gibson", cate:1346, created:false},
        {name:"PRS", cate:1348, created:false},
        {name:"Suhr", cate:266, created:false},
        {name:"John Cruz", cate:1803, created:false},
        {name:"Don Grosh", cate:258, created:false},
        {name:"Tom Anderson", cate:272, created:false},
        {name:"Xotic", cate:1225, created:false},
        {name:"Zemaitis", cate:1852, created:false},
        {name:"Knaggs", cate:788, created:false},
        {name:"LSL", cate:604, created:false},
        {name:"Fodera", cate:1536, created:false},
    ],
    "Guitars 2" : [
        {name:"Bacchus", cate:1379, created:false},
        {name:"Ibanez", cate:1377, created:false},
        {name:"Momose(Japan)", cate:1864, created:false},
        {name:"Seventy Seven(Hollowbody)", cate:1707, created:false},
        {name:"Musicman", cate:277, created:false},
        {name:"Epiphone", cate:1378, created:false},
        {name:"Schecter", cate:1274, created:false},
        {name:"Gretsch", cate:1439, created:false},
        {name:"Jackson", cate:1720, created:false},
        {name:"Strandberg", cate:1540, created:false},
        {name:"Charvel", cate:1230, created:false},
        {name:"D'Angelico", cate:1733, created:false},
    ],
    "Bass 1" : [
        {name:"Fodera", cate:962, created:false},
        {name:"Alieva Coppolo",cate:1110,  created:false},
        {name:"Fender", cate:961, created:false},
        {name:"Lakland", cate:965, created:false},
        {name:"MTD", cate:964, created:false},
        {name:"F-BASS", cate:966, created:false},
        {name:"PRS", cate:969, created:false},
        {name:"Mayones", cate:1858, created:false},
        {name:"Momose (Japan)", cate:1867, created:false},
        {name:"SAITO", cate:1892, created:false},
    ],
    "Bass 2" : [
        {name:"Ibanez", cate: 974, created:false},
        {name:"Dingwall", cate: 1542, created:false},
        {name:"Spector", cate: 1562, created:false},
        {name:"Epiphone", cate: 1200, created:false},
        {name:"Sandberg", cate: 1151, created:false},
        {name:"Sire", cate: 1842, created:false},
        {name:"Strandberg", cate: 1546, created:false},
        {name:"Schecter", cate: 1615, created:false},
        {name:"Jackson", cate: 1737, created:false},
    ],
    "Acoustic 1" : [ // 전부 가져옴
        {name:"Martin",cate:883, created:false},
        {name:"Taylor",cate:912, created:false},
        {name:"Gibson",cate:913, created:false},
        {name:"PRS",cate:932, created:false},
        {name:"Furch",cate:1581, created:false},
        {name:"Lakewood",cate:1078, created:false},
        {name:"Maton",cate:1195, created:false},
        {name:"Guild",cate:1570, created:false},
        {name:"LAG",cate:1519, created:false},
        {name:"Lava Music",cate:1505, created:false},
        {name:"Huss&Dalton",cate:915, created:false},
        {name:"Santa Cruz",cate:916, created:false},
    ],
    "Acoustic 2" : [ // 전부 가져옴
        {name:"Sigma", cate:931, created:false},
        {name:"Epiphone", cate:927, created:false},
        {name:"Cort",cate:1592,  created:false},
        {name:"Cordoba", cate:1429, created:false},
        {name:"Godin", cate:1857, created:false},
        {name:"Sheeran by Lowden", cate:1676, created:false},
        {name:"Veelah", cate:1526, created:false},
        {name:"Gopherwood", cate:1576, created:false},
        {name:"Parkwood", cate:1627, created:false},
        {name:"Fender", cate:1233, created:false},
        {name:"Ibanez", cate:1837, created:false},
        {name:"Gretsch", cate:1574, created:false},
        {name:"Admira", cate:1510, created:false},
        {name:"Washburn", cate:924, created:false},
        {name:"Roxy", cate:925, created:false},
    ],
    "Recording" : [
        {name:"Audio Interface", created:false},
        {name:"Load Box & IR", created:false},
        {name:"MIC", created:false},
        {name:"Monitor Speaker", created:false},
        {name:"D.I", created:false},
    ],
    "Amp" : [
        {name:"Suhr", created:false},
        {name:"PRS", created:false},
        {name:"Bogner", created:false},
        {name:"Hughes and Kettner", created:false},
        {name:"Revv", created:false},
        {name:"Fender", created:false},
        {name:"Marshall", created:false},
    ],
    "Pedals" : [ // 너무 많아서 인지도 있는 페달만 우선 기입
        {name:"Bogner", created:false},
        {name:"Suhr", created:false},
        {name:"Friedman", created:false},
        {name:"Vertex ", created:false},
        {name:"Revv Amplication", created:false},
        {name:"Mad Professor", created:false},
        {name:"Vemuram", created:false},
    ],
    "Acc/Parts ": [
        {name:"Gotoh Parts", created:false},
        {name:"Gibson Parts", created:false},
        {name:"PRS Parts & ACC", created:false},
        {name:"Gruvgear ", created:false},
        {name:"Gator", created:false},
        {name:"픽업", created:false},
        {name:"스트랩", created:false},
        {name:"관리용품", created:false},
    ],
    "New Arrival":[],
    "Sale":[],
    "Used/Outlet" : [ // 너무 많아서 인지도 있는 페달만 우선 기입
        {name:"Used(중고제품)", created:false},
        {name:"Outlet(아웃렛)", created:false},
    ],
}
export const headlineMiddleInfo=[
    "로그인", "회원가입", "장바구니", "주문조회", 
]

